Issues/67 add job
sounit-organization/job_search_app_front pull request #89
Opened 2022-07-13 23:51 UTC by azar-barfipour

## issue numbers to close them automatically

- fixed #

2022-07-13 23:53 UTC, azar-barfipour commented
Hi. Please review my code. thanks:)

2022-07-13 23:54 UTC, azar-barfipour commented
please review

2022-07-14 03:52 UTC, SOunit requested changes
thanks! I added some comments. pls check and fix them!

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +const JobForm: FC<Props> = (props) => {
name should be `EditJobForm`

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  const [jobDesc, setJobDesc] = useState("");
- jobTitle
- jobCity
- jobCompany
- jobPayment
- jobDesc

let's replace them with `useForm`

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  const [jobDesc, setJobDesc] = useState("");
jobPayment can be string.
backend will make it number.

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  // const submitHandler: React.FormEventHandler<HTMLFormElement> = (event) => {
pls remove all comments

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  // const submitHandler: React.FormEventHandler<HTMLFormElement> = (event) => {
or pls put `FIXME` comment if you want to keep comment stay

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +    await axios.post(
let's use react query package.

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  const titleChangeHandler = (event: ChangeEvent<HTMLInputElement>) => {
all input handler can be replaced with `valueChangeHandler` from `useForm`

2022-07-14 03:52 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +  const titleChangeHandler = (event: ChangeEvent<HTMLInputElement>) => {
pls check `EditSkillForm.tsx`

2022-07-14 03:52 UTC, SOunit commented on src/services/jobsHttpClient.adapter.ts
> +export const getJobs = (): Promise<IJob[]> => {
thanks for adding code, but do you need these logic for this issue?
pls add minimum code for your issues.

issue name and PR content should match in working environment, so let's follow same approach here too!

2022-07-14 03:58 UTC, SOunit requested changes

2022-07-14 03:58 UTC, SOunit commented on src/constants/constants.ts
> +export const REACT_QUERY_KEY_JOBS = "skills";
value should be "jobs"?

2022-07-14 04:05 UTC, SOunit requested changes

2022-07-14 04:05 UTC, SOunit commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +    await axios.post(
but sorry, as a first step, it's ok using axios :)

2022-07-15 02:45 UTC, azar-barfipour commented on src/presentation/components/organisms/CreateJob/EditJobForm.tsx
> +const JobForm: FC<Props> = (props) => {
done

2022-07-19 00:17 UTC, azar-barfipour reviewed
lgtm

2022-07-19 00:22 UTC, SOunit approved these changes
lgtm

2022-07-19 00:37 UTC, merged